import type { RankName } from "./scoring/types";

/**
 * Decorative portrait ring per rank, generated by scripts/gen-rings.mjs.
 *
 * Hollow is deliberately null: a husk gets no regalia, so it keeps the plain
 * coloured border it always had. Every other rank swaps that border for art.
 */
export interface RankRing {
  /** Path under public/, PNG with keyed alpha, square. */
  src: string;
  /**
   * Inner hole diameter as a fraction of the ring's own width, measured at the
   * median angle. The five rings don't share a band thickness — Knight's is
   * thin, Undead's is fat — so the avatar is sized from this rather than from a
   * constant, keeping the outer size stable while the portrait fills the hole.
   *
   * Median rather than minimum on purpose: ornaments at the cardinal points jut
   * well inside the band, and letting them overlap the portrait is the look.
   */
  innerRatio: number;
}

export const RANK_RING: Record<RankName, RankRing | null> = {
  "Hollow": null,
  "Undead": { src: "/img/rings/undead.png", innerRatio: 0.555 },
  "Knight": { src: "/img/rings/knight.png", innerRatio: 0.703 },
  "Abyss Walker": { src: "/img/rings/abysswalker.png", innerRatio: 0.596 },
  "Lord": { src: "/img/rings/lord.png", innerRatio: 0.620 },
  "Soul of Cinder": { src: "/img/rings/cinder.png", innerRatio: 0.573 },
};

/**
 * Medallion box size, mobile and sm-up.
 *
 * `ring` is the outer box for a rank with art — fixed across ranks so a column
 * does not reflow between a thin band and a fat one; the portrait inside varies
 * instead. `portrait` is the plain circle Hollow gets, which has no outer art to
 * reserve space for and so keeps the size it has always had in each context.
 */
export const MEDALLION_SIZE = {
  profile: {
    ring: { base: 260, sm: 300 },
    portrait: { base: 160, sm: 176 },
  },
  duel: {
    ring: { base: 260, sm: 300 },
    portrait: { base: 176, sm: 208 },
  },
} as const;

export type MedallionVariant = keyof typeof MEDALLION_SIZE;
