import type { RankName } from "./scoring/types";

/**
 * Decorative portrait ring per rank, generated by scripts/gen-rings.mjs.
 *
 * Hollow is deliberately null: a husk gets no regalia, so it keeps the plain
 * coloured border it always had. Every other rank swaps that border for art.
 */
export interface RankRing {
  /** Path under public/, PNG with keyed alpha, square. */
  src: string;
  /**
   * Inner hole diameter as a fraction of the ring's own width, measured at the
   * median angle. The five rings don't share a band thickness — Knight's is
   * thin, Undead's is fat — so the avatar is sized from this rather than from a
   * constant, keeping the outer size stable while the portrait fills the hole.
   *
   * Median rather than minimum on purpose: ornaments at the cardinal points jut
   * well inside the band, and letting them overlap the portrait is the look.
   */
  innerRatio: number;
}

export const RANK_RING: Record<RankName, RankRing | null> = {
  "Hollow": null,
  "Undead": { src: "/img/rings/undead.png", innerRatio: 0.555 },
  "Knight": { src: "/img/rings/knight.png", innerRatio: 0.703 },
  "Abyss Walker": { src: "/img/rings/abysswalker.png", innerRatio: 0.596 },
  "Lord": { src: "/img/rings/lord.png", innerRatio: 0.620 },
  "Soul of Cinder": { src: "/img/rings/cinder.png", innerRatio: 0.573 },
};

/**
 * Outer size of the ring box. Fixed across ranks so the page doesn't reflow
 * between a thin ring and a fat one; the avatar inside is what varies.
 */
export const RING_SIZE = { base: 260, sm: 300 } as const;

/** Avatar diameter that fills a ring of `ringSize`. */
export function avatarSize(ring: RankRing, ringSize: number): number {
  return Math.round(ringSize * ring.innerRatio);
}
